[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NEXT_PUBLIC_SANITY_PROJECT_ID = "pso85crw"
  NEXT_PUBLIC_SANITY_DATASET = "production"
  NODE_VERSION = "20"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, s-maxage=3600"
